Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

df = pd.read_csv(
    "raman.txt", delimiter="\t", index_col=0, names=["wavenumber", "intensity"]
)
df[(df.index >= 1000) & (df.index < 1500)].plot();
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m df [38;5;241m=[39m pd[38;5;241m.[39mread_csv(
[1;32m      4[0m     [38;5;124m"[39m[38;5;124mraman.txt[39m[38;5;124m"[39m, delimiter[38;5;241m=[39m[38;5;124m"[39m[38;5;130;01m\t[39;00m[38;5;124m"[39m, index_col[38;5;241m=[39m[38;5;241m0[39m, names[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mwavenumber[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mintensity[39m[38;5;124m"[39m]
[1;32m      5[0m )
[1;32m      6[0m df[(df[38;5;241m.[39mindex [38;5;241m>[39m[38;5;241m=[39m [38;5;241m1000[39m) [38;5;241m&[39m (df[38;5;241m.[39mindex [38;5;241m<[39m [38;5;241m1500[39m)][38;5;241m.[39mplot();

[0;31mModuleNotFoundError[0m: No module named 'pandas'

